### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by boredmage** [tuhamworld/ReactFacts#1]
The component folder name is in Capital **C**omponent while the the import is in small letter **c**omponent
![Deploy errorPointer](https://github.com/tuhamworld/ReactFacts/assets/51055890/27b5d785-b803-4751-9fbc-2c23e1bf2e14)

**Comment by tuhamworld** [comment]
That's interesting as the component folder name on my local directory is in **small letters** which is the same as my **import**. Thank you for pointing that out, would make the necessary changes and try deploying again

 
![components_small_folder](https://github.com/tuhamworld/ReactFacts/assets/52820977/ae82506f-896f-4da9-acca-55f0da4d750c)

**Comment by tuhamworld** [comment]
The issue has been fixed. It was due to the capitalization😐

Thank you so much @Qudusayo for pointing this out!

It is highly appreciated :)
